# Generated by Django 6.0.7 on 2026-08-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_like_options_category_name_en_category_name_fa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
