# Generated by Django 6.0.7 on 2026-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for homepage cards (max 300 chars)', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for post cards', null=True, upload_to='posts/'),
        ),
    ]
