# Generated by Django 6.0.7 on 2026-08-13 03:34

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_excerpt_post_featured_image'),
    ]

    operations = [
        TrigramExtension(),
    ]
