# Generated by Django 6.0.7 on 2026-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_enable_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='helpful_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='helpful_yes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
